### ISSUE TITLE
nbpersian ES6

### ISSUE THREAD

**Issue by mmdsharifi** [msudgh/nbpersian#1]
Hi, masood
thanks for this great work :+1:   . 
I also create a repository for ES6 version of codes.
hope useful 
https://github.com/mmdsharifi/nbpersian-code

**Comment by imasood** [comment]
Hi Mohamad.
your work is very good.
i will add into main repository, soon.
thanks 👏

**Comment by masoudgs** [comment]
@mmdsharifi Thanks for your great job but the book's source code is tiny and I think didn't need `ES6` version which I prefer to source code be in the way of the book.
