### ISSUE TITLE
Move everything to Github(PDF and also the online website)

### ISSUE THREAD

**Issue by farooqkz** [msudgh/nbpersian#5]
When Github can be used for these, why using external programs/websites?
For online reading you can use Github pages and for PDF you can release the book, use the repo itself or use Github pages.

**Comment by masoudgs** [comment]
You're right and I see but Github doesn't show RTL typeface as well and also I tried to serve book on the Gitbook but it was the same as the Github. I reviewed the Gitbook again today and it seems that support for right-to-left languages has improved.

**Comment by farooqkz** [comment]
I never talked about Gitbook, I was talking about releasing the book(its pdf) using Github, or using this repo for the PDF, and for online reading, Github pages, just use [Github pages](https://pages.github.com/) for online reading, less cost for you and also more stability.

**Comment by masoudgs** [comment]
Sorry for late response, Since I used my blog address in the book translation and used it as the reference in various sites this movement is impossible.
